# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '11ShoppingList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 11ShoppingList
  pod 'RealmSwift', '~>10'
  pod 'JGProgressHUD'
  pod 'Zip', '~> 2.1'
  pod 'Toast-Swift', '~> 5.0.1'


end
